### ISSUE TITLE
plot error

### ISSUE THREAD

**Issue by rwdudley-usgs** [USGS-R/DVstats#1]
Following the example in the 7Q10 vignette (p. 19), when I issue the commands

```
setSweave("SevenDay_07", 5, 5)
plot(xClimY.frq, which="default", set.up=FALSE)
graphics.off()
```

I get this error message and the plot does not render.
`Error in getDist.fcn(distribution, "q") : 
  Distribution function for gev not found.`

**Comment by dlorenz-usgs** [comment]
The distribution function for gev is in the evd package. It should be
available, but try library(evd) to make sure that the function is available.

**Comment by rwdudley-usgs** [comment]
Thank you!

_Robert W. Dudley, PE_
_Hydrologist_ \* Office: (207) 626-6615 \* Fax: (207) 622-8204 \* Email:
rwdudley@usgs.gov
_U.S. Department of the Interior | *_U.S. Geological Survey | New England
Water Science Center*
196 Whitten Road \* Augusta, ME 04330 \* _https://profile.usgs.gov/rwdudley
https://profile.usgs.gov/rwdudley_
